[Variables]
IconName=TuneFluent
;Default = Tune
StartText=Volume Mixer
;Default = Volume Mixer

W=450
MinH=0
;Default = 0

Font=Segoe UI
Scale=1
;User
Stroke=0
R=0
;Default = 15
SliderStyle=Fluent
;Default = Round

Position=BR
;User
ScreenPadding=0
;Default = 20
AnimationDisplacement=30
;Default = 30

Animated=1
EaseType=OutSine
AniDir=Bottom
AniSteps=10

Blur=Acrylic
;Default = None
BlurCorner=None
;Default = None

Accent=35,159,255
Alpha=150
Color=36,36,36
Border=54,54,54
FontColor=255,255,255
DarkColor=190,190,190
BoxBorder=80,80,80
BoxColor=60,60,60

BackgroundMod=0

;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;║ METERSTYLES                                                                                          ║
;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝


[BoldText]
FontFace=#Font#
FontWeight=800
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1

[SemiBoldText]
FontFace=#Font#
FontWeight=500
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1

[RegularText]
FontFace=#Font#
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1
