[Variables]
IconName=Tune
;Default = Tune
StartText=Volume Mixer
;Default = Volume Mixer

W=500
MinH=0
;Default = 0

Font=Poppins
Scale=1
;User
Stroke=0
CircSize=6
;Default = 6
R=15
;Default = 15

Position=BR
;User
ScreenPadding=20
;Default = 20
AnimationDisplacement=30
;Default = 30

Animated=1
EaseType=OutSine
AniDir=Bottom
AniSteps=10

Blur=None
;Default = None
BlurCorner=None
;Default = None

Accent=242, 52, 0
Alpha=255
Color=12,12,12
Border=28,28,28
FontColor=242,240,255
DarkColor=120,120,120
BoxBorder=35,35,35
BoxColor=35,35,35

BackgroundMod=1

;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;║ METERSTYLES                                                                                          ║
;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝


[BoldText]
FontFace=#Font#
FontWeight=800
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1

[SemiBoldText]
FontFace=#Font#
FontWeight=500
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1

[RegularText]
FontFace=#Font#
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1
